name: Build CallieOS ISO

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Liberar espaço em disco no servidor (Essencial)
        run: |
          echo "=== Espaço livre antes da limpeza ==="
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /usr/local/share/powershell
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/.ghcup
          docker system prune -a --volumes -f
          echo "=== Espaço livre após a limpeza ==="
          df -h

      - name: Executar Script de Build da ISO
        run: |
          chmod +x build.sh
          sudo ./build.sh

      - name: Enviar ISO como Artefato
        uses: actions/upload-artifact@v4
        with:
          name: CallieOS-Mint-XFCE-ISO
          path: ./*.iso
