name: Build CallieOS ISO

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v4

      - name: Executar Script de Build da ISO
        run: |
          chmod +x build.sh
          sudo ./build.sh
